# Install Binaries
brew 'bash' # Latest Bash version
brew 'bat' # "cat" on steroids
brew 'coreutils' # Those that come with macOS are outdated
brew 'git'
brew 'gh'
brew 'grep'
brew 'pkg-config' # https://github.com/driesvints/dotfiles/issues/20
brew 'tree'
brew 'awscli'
brew 'gnu-sed'
brew 'nvim'
brew 'tmux'
brew 'netcat'
brew 'asdf'
brew 'direnv'
brew 'jq'
brew 'yq'
brew 'sops'
brew 'pre-commit'
brew 'aws-vault'
brew 'stern'
brew 'kubelogin'
brew 'helmfile'
brew 'tflint'
brew 'tfsec'
brew 'checkov'
brew 'hadolint'
brew 'krew'
# brew 'zsh'
# brew 'zsh-completions'

# Development
brew 'nginx'
brew 'pyenv'
brew 'prettier'
brew 'hashicorp/tap/terraform'
brew 'terragrunt'
brew 'terraform-docs'
brew 'argocd'
brew 'fzf'
brew 'go'
brew 'docker-completion'
brew 'docker-credential-helper'
brew 'e1s'
brew 'eks-node-viewer'
brew 'eksctl'
brew 'ffmpeg'
brew 'helm'
brew 'k9s'
brew 'kubectl'
brew 'kustomize'
brew 'kubectx'
brew 'kubesess'
brew 'make'
brew 'nvm'
brew 'codex'

# Apps
cask 'caffeine'
cask 'rectangle'
cask 'tableplus'
cask 'alfred'
cask 'cleanshot'
cask 'dropbox'
cask 'obsidian'
cask 'sublime-text'
cask 'visual-studio-code'
cask '1password'
cask 'slack'
cask 'contexts'
cask 'spotify'
cask 'google-drive'
cask 'calibre'
cask 'zoom'
cask 'gcloud-cli'
cask 'kitty'
cask 'rancher'
cask 'session-manager-plugin'
cask 'claude-code'
cask 'chatgpt'


# Install Mac App Store apps
mas 'Keynote', id: 409183694
mas 'Numbers', id: 409203825
mas 'Pages', id:409201541
